### ISSUE TITLE
Get Cursor using Dropbox Python API

### ISSUE THREAD

**Issue by gfleetwood** [dropbox/mdwebhook#9]
I'm trying to implemented a trigger when a file is uploaded (possibly by me) to a dropbox account. It's unclear how to get the folder where the change occurred from the info in the web hook without assuming a redis database exists. How do I get a cursor just using the python API?

**Comment by greg-db** [comment]
Dropbox webhooks only tell you when something has changed in the indicated account(s), not what specifically has changed. To find out what has changed, you'll need to call the API to list the folder/changes.

With [the Dropbox Python SDK](https://github.com/dropbox/dropbox-sdk-python), you can do so via the [`files_list_folder`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.Dropbox.files_list_folder) and [`files_list_folder_continue`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.Dropbox.files_list_folder_continue) methods.
